### ISSUE TITLE
Snackbar should be animate upwards

### ISSUE THREAD

**Issue by idanwe** [255kb/md-snackbars#2]
According to the Google's Material Design specifications  snackbar should be animate upwards.

Maybe you can use slideDown() / slideUp() instead of fadeIn

**Comment by daviddarnes** [comment]
Hi, I've also noticed this. I do like the fade in animation style but would it be possible to state options?

Edit: As a temporary fix I've used CSS animations to make them slide up as they appear.

```
.md-snackbar-shown {
    -webkit-animation: slideup .4s;
    animation: slideup .4s;
}

@keyframes slideup {
    from { transform: translate(0, 200px); }
    to { transform: translate(0, 0); }
}

@-webkit-keyframes slideup {
    from { -webkit-transform: translate(0, 200px); }
    to { -webkit-transform: translate(0, 0); }
}
```

Not ideal but it brings it in closer with the Material Design style.

**Comment by 255kb** [comment]
I just released v1.3.0 with fade in and slide up animations

**Comment by daviddarnes** [comment]
@255kb beautiful, thanks for this and creating the project!

**Comment by 255kb** [comment]
you are welcome, glad you are using it :)

**Comment by idanwe** [comment]
@255kb thank you!
