### ISSUE TITLE
Hooks?

### ISSUE THREAD

**Issue by alanshaw** [255kb/md-snackbars#5]
Would be awesome to have `onShow` and `onHide` hooks for when the snackbar finally makes it onto the screen and when it exits.

Perhaps context (`this`) is the DOM element - so that I can attach listeners to links in the HTML, like the UNDO link as shown in the [google snackbar design specs](http://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs)

``` js
MDSnackbars.show({
  onShow () {
    $(this).find('a.undo').click(() => alert('TODO: Undo'))
  }
})
```

**Comment by 255kb** [comment]
Sorry this package is not maintained anymore, I won't fix bugs or add new features
