### ISSUE TITLE
ios click to close not working

### ISSUE THREAD

**Issue by krem06** [255kb/md-snackbars#7]
Hello,

I am having an issue to close snackbar on click. If I test your demo with a browser the snackbar does close when I click on it, but using ios safari on mobile it doesn't... 

Can you confirm you get the same behaviour ? Any idea what could be happening ?

Thanks for this awesome module ;)

**Comment by 255kb** [comment]
Sorry this package is not maintained anymore, I won't fix bugs or add new features
